# Generated by Django 3.1.7 on 2021-03-01 09:19

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='bank_acc_no',
            field=models.CharField(max_length=30, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\-\\d+)*\\Z'), code='invalid', message='Enter only digits number')], verbose_name='bank account no.'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='deposit_type',
            field=models.CharField(choices=[('netto', 'Netto'), ('gross', 'Gross')], default='netto', max_length=10, verbose_name='deposit'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='product_type',
            field=models.CharField(choices=[('hypn', 'HYPN'), ('isprint', 'ISPRINT')], default='hypn', max_length=20),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='transaction_type',
            field=models.CharField(choices=[('overbooking', 'Overbooking'), ('trans_or_rtgs', 'Transaction or RTGS'), ('cheque_or_giro', 'Cheque or Giro No.')], default='trans_or_rtgs', max_length=30, verbose_name='transaction type'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='bank_acc_no',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\-\\d+)*\\Z'), code='invalid', message='Enter only digits number')], verbose_name='bank account no.'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='investor_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('corporate', 'Corporate')], default='individual', max_length=20, verbose_name='investor type'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='mobile1',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits number')], verbose_name='primary mobile no.'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='mobile2',
            field=models.CharField(blank=True, default='', max_length=30, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits number')], verbose_name='secondary mobile no.'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='national_id_card_no',
            field=models.CharField(max_length=30, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits number'), django.core.validators.MaxLengthValidator(16), django.core.validators.MinLengthValidator(16)], verbose_name='national id card no'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='phone',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\-\\d+)*\\Z'), code='invalid', message='Enter only digits number')], verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='postal_code',
            field=models.CharField(default='', max_length=10, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits number')], verbose_name='postal code'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='tax_id_no',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='tax id no.'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Currency in Rp (Rupiah)', max_digits=16, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='bank_acc_no',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\-\\d+)*\\Z'), code='invalid', message='Enter only digits number')], verbose_name='bank account no.'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='form_no',
            field=models.CharField(help_text='e.x: 1021031', max_length=7, unique=True, verbose_name='formulir no.'),
        ),
    ]
