# Generated by Django 3.1.7 on 2021-03-01 09:19

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='bank_acc_no',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\-\\d+)*\\Z'), code='invalid', message='Enter only digits number')], verbose_name='bank account no.'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=5, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='mobile1',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\-\\d+)*\\Z'), code='invalid', message='Enter only digits number')], verbose_name='primary mobile no.'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='mobile2',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\-\\d+)*\\Z'), code='invalid', message='Enter only digits number')], verbose_name='secondary mobile no.'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='national_id_card_no',
            field=models.CharField(max_length=30, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits number'), django.core.validators.MaxLengthValidator(16), django.core.validators.MinLengthValidator(16)], verbose_name='national id card no'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='phone',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\-\\d+)*\\Z'), code='invalid', message='Enter only digits number')], verbose_name='phone no.'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='photo',
            field=models.ImageField(default='', upload_to='agents/photos/', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='position',
            field=models.CharField(choices=[('finconsultant', 'Financial Consultant'), ('manager', 'Manager'), ('director', 'Director')], default='finconsultant', max_length=50, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='postal_code',
            field=models.CharField(default='', max_length=10, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits number')], verbose_name='postal code'),
        ),
    ]
