# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-21 11:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=7)),
                ('address', models.TextField(verbose_name='address')),
                ('postal_code', models.CharField(default=b'', max_length=10, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code=b'invalid', message=b'Enter only digits number')], verbose_name='postal code')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\-\\d+)*\\Z'), code=b'invalid', message=b'Enter only digits number')], verbose_name='phone no.')),
                ('city', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.City')),
                ('province', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.Province')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
