# Generated by Django 3.1.7 on 2021-03-01 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_auto_20170629_1943'),
        ('utils', '0002_auto_20170622_1500'),
    ]

    operations = [
    ]
